version: "3"
services:
  redis:
    image: redis:alpine
    env_file: .env
    restart: on-failure
    ports:
      - "6379:6379"
  db:
    image: postgres:16.3
    env_file: .env
    user: postgres
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build: .
    env_file: .env
    command: sh -c "python3 main.py"
    restart: always
    depends_on:
      - db
      - redis

volumes:
  pgdata:

